// Code generated by goctl. DO NOT EDIT!
// Source: pRpc1.proto

package server

import (
	"context"

	"github.com/pz2147/p-rpc-1/internal/logic"
	"github.com/pz2147/p-rpc-1/internal/svc"
	"github.com/pz2147/p-rpc-1/prpc1"
)

type PRpc1Server struct {
	svcCtx *svc.ServiceContext
}

func NewPRpc1Server(svcCtx *svc.ServiceContext) *PRpc1Server {
	return &PRpc1Server{
		svcCtx: svcCtx,
	}
}

func (s *PRpc1Server) Ping(ctx context.Context, in *prpc1.Request) (*prpc1.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
