// Code generated by goctl. DO NOT EDIT!
// Source: pRpc1.proto

package prpc1client

import (
	"context"

	"github.com/pz2147/p-rpc-1/prpc1"

	"github.com/tal-tech/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = prpc1.Request
	Response = prpc1.Response

	PRpc1 interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultPRpc1 struct {
		cli zrpc.Client
	}
)

func NewPRpc1(cli zrpc.Client) PRpc1 {
	return &defaultPRpc1{
		cli: cli,
	}
}

func (m *defaultPRpc1) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := prpc1.NewPRpc1Client(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
